export const SEARCHING_PLANET = 'SEARCHING_PLANET';
export const UPDATE_PLANETS_SEARCH_DICTIONARY =
  'UPDATE_PLANETS_SEARCH_DICTIONARY';
export const UPDATE_CURRENT_PLANET_DICTIONARY =
  'UPDATE_CURRENT_PLANET_DICTIONARY';
export const UPDATE_CURRENT_PLANET = 'UPDATE_CURRENT_PLANET';
export const UPDATE_VIEW_LIST = 'UPDATE_VIEW_LIST';
