export const SEARCHING_PLANET = 'SEARCHING_PLANET';
export const UPDATE_PLANETS_SEARCH_DICTIONARY =
  'UPDATE_PLANETS_SEARCH_DICTIONARY';
export const UPDATE_CURRENT_PLANET_DICTIONARY =
  'UPDATE_CURRENT_PLANET_DICTIONARY';
export const UPDATE_CURRENT_PLANET = 'UPDATE_CURRENT_PLANET';
export const UPDATE_CURRRENT_KEYWORD = 'UPDATE_CURRRENT_KEYWORD';
export const IS_LOADING_MORE = 'IS_LOADING_MORE';
export const UPDATE_NEXT_URL = 'UPDATE_NEXT_URL';
